include: package:flutter_lints/flutter.yaml


linter:
  rules:
    unawaited_futures: false
    prefer_relative_imports: true
    curly_braces_in_flow_control_structures: false
    avoid_single_cascade_in_expression_statements: false
    non_constant_identifier_names: false
    avoid_renaming_method_parameters: false
    prefer_const_constructors: false
    no_leading_underscores_for_local_identifiers: false
    library_private_types_in_public_api: false

analyzer:
  errors:
    prefer_relative_imports: warning
    