targets:
  $default:
    builders:
      nop_gen:
        generate_for:
          - lib/database/**
      nop_gen:nop_isolate_event:
        generate_for:
          - lib/event/**
      json_serializable:
        generate_for:
          - lib/data/**