name: shudu
description: 小说阅读·仿

publish_to: none
version: 2.1.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # animations: ^2.0.0
  # audio_service: ^0.17.1
  async: any
  # characters: ^1.1.0
  # collection: ^1.15.0
  cupertino_icons: ^1.0.0
  device_info: ^2.0.1
  dio: ^4.0.1
  equatable: ^2.0.5
  fake_async: ^1.2.0
  # flutter_bloc: ^7.0.0
  flutter_local_notifications: ^12.0.3
  flutter_sticky_header: ^0.6.0
  flutter_native_splash: ^2.0.5
  # flutter_tts: ^3.2.2
  # flutter_displaymode: ^0.3.2
  # get: ^4.3.6
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  # hot_fix:
  #   path: ../packages/hot_fix
  infinite_scroll_pagination: ^3.1.0
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logger: ^1.0.0
  lpinyin: ^2.0.3
  path: any
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  # provider: ^6.0.2
  screen_brightness: ^0.2.2
  stream_channel: ^2.1.0
  stack_trace: ^1.10.0
  url_launcher: ^6.0.3
  useful_tools:
    git:
      url: https://github.com/sersr/useful_tools.git
  video_player: ^2.1.0
  wakelock: ^0.6.1+1
  infinite_listview: ^1.1.0
  pull_to_refresh: ^2.0.0
  # bitsdojo_window: ^0.1.1+1
  # web_socket_channel: ^2.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  nop: ^0.0.3+1
  nop_db:
    git:
      url: https://github.com/sersr/nop_db.git
  flutter_nop: ^2.1.1+1
  nop_db_sqlite:
    git:
      url: https://github.com/sersr/nop_db_sqlite.git
  bangs:
    git:
      url: https://github.com/sersr/bangs.git
  nop_db_sqflite:
    git:
      url: https://github.com/sersr/nop_db_sqflite.git
  process: ^4.2.3
  args: ^2.3.0
  file: ^6.1.2
  memory_info: ^0.0.2
  crypto: ^3.0.1
  archive: ^3.1.6
  http: ^0.13.4
  android_external_storage: ^0.1.0
  battery_plus: ^3.0.2
  flutter_colorpicker: ^1.0.2
  get_it: ^7.2.0
  protobuf: ^2.0.1
  dartz: ^0.10.1
  freezed_annotation: ^2.0.3
  js: any
  logging: ^1.0.2
  scrollable_positioned_list: ^0.3.5
  syncfusion_flutter_charts: ^20.3.56
  vector_math: any
  nop_annotations: 0.2.0
  # flutter_hooks:
  #   git: https://github.com/rrousselGit/flutter_hooks

# 下面为本地覆盖，如果本地没有对应插件需要手动注释
# dependency_overrides:
# useful_tools:
#   path: ../packages/useful_tools
# flutter_nop:
#   path: ../packages/flutter_nop
# nop:
#   path: ../packages/nop
# nop_db:
#   path: ../packages/nop_db
# nop_annotations:
#   path: ../packages/nop_annotations
# nop_db_sqlite:
#   path: ../packages/nop_db_sqlite
# bangs:
#   path: ../packages/bangs
# nop_db_sqflite:
#   path: ../packages/nop_db_sqflite
# nop_gen:
#   path: ../packages/nop_gen

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  freezed: ^2.0.3+1
  # hive_generator: any
  json_serializable: ^6.1.3
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  nop_gen: ^0.2.1
  # retrofit_generator: ^2.0.0-beta3

flutter:
  uses-material-design: true
  # fonts:
  # - family: SourceHanSerif
  #   fonts:
  #     - asset: assets/fonts/SourceHanSerif-Regular.ttc
  #     - asset: assets/fonts/SourceHanSerif-Bold.ttc
  #       weight: 700
  # - family: NotoSansSC
  #   fonts:
  #     - asset: assets/fonts/NotoSansSC-Regular.otf
  # - asset: assets/fonts/NotoSansSC-Bold.otf
  #       weight: 700
  # - family: RobotoMono
  #   fonts:
  #     - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
  # - family: SourceHanSans
  #   fonts:
  #     - asset: assets/fonts/SourceHanSansCN/SourceHanSans-Regular.otf
  # - family: SourceHanSansSC
  #   fonts:
  #     - asset: assets/fonts/SourceHanSansSC-Regular.otf
  #     - asset: assets/fonts/SourceHanSansSC-Bold.otf
  #       weight: 700
