name: shudu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.0
  built_collection: ^5.0.0
  battery: ^2.0.1
  collection: ^1.15.0
  cupertino_icons: ^1.0.0
  device_info: ^2.0.0
  dio: ^4.0.0
  equatable: ^2.0.0
  flutter_bloc: ^7.0.0
  flutter_sticky_header: ^0.6.0
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  http: ^0.13.1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  logger: ^1.0.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  retrofit: ^2.0.0-beta1
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0
  url_launcher: ^6.0.3
  video_player: ^2.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  bangs:
    path: ./plugins/bangs
  pull_to_refresh:
    path: ./plugins/pull_to_refresh
  shared_preferences: ^2.0.5
  # flutter_hooks:
  #   git: https://github.com/rrousselGit/flutter_hooks

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.0.1
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  pedantic: ^1.11.0
  retrofit_generator: ^2.0.0-beta3
  
flutter:
  uses-material-design: true
  fonts:
    # - family: SourceHanSerif
    #   fonts:
    #     - asset: assets/fonts/SourceHanSerif-Regular.ttc
    #     - asset: assets/fonts/SourceHanSerif-Bold.ttc
    #       weight: 700
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.otf
        # - asset: assets/fonts/NotoSansSC-Bold.otf
    #       weight: 700
    # - family: SourceHanSansSC
    #   fonts:
    #     - asset: assets/fonts/SourceHanSansSC-Regular.otf
    #     - asset: assets/fonts/SourceHanSansSC-Bold.otf
    #       weight: 700