name: shudu
description: 小说阅读·仿

publish_to: none
version: 1.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # animations: ^2.0.0
  battery: ^2.0.2
  # characters: ^1.1.0
  # collection: ^1.15.0
  cupertino_icons: ^1.0.0
  device_info: ^2.0.1
  dio: ^4.0.0
  equatable: ^2.0.2
  fake_async: ^1.2.0
  # flutter_bloc: ^7.0.0
  flutter_sticky_header: ^0.6.0
  flutter_displaymode: ^0.3.2
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  json_annotation: ^4.0.1
  logger: ^1.0.0
  lpinyin: ^2.0.3
  path: ^1.8.0
  path_provider: ^2.0.1
  permission_handler: ^8.1.3
  provider: ^5.0.0
  stream_channel: ^2.1.0
  stack_trace: ^1.10.0
  url_launcher: ^6.0.3
  useful_tools:
    path: ../useful_tools
  video_player: ^2.1.0
  # web_socket_channel: ^2.1.0
  carousel_slider: ^4.0.0-nullsafety.0
  bangs:
    git:
      url: https://github.com/sersr/bangs
      ref: master
  # pull_to_refresh: ^2.0.0

  # shared_preferences: ^2.0.5
  nop_db:
    git:
      url: https://github.com/sersr/nop_db
      ref: master
  # flutter_hooks:
  #   git: https://github.com/rrousselGit/flutter_hooks

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^1.1.0
  json_serializable: ^4.1.2
  flutter_lints: ^1.0.0
  # nop_db_gen:
  #   git: 
  #     url: https://github.com/sersr/nop_db_gen
  #     ref: master
  nop_db_gen:
    path: ../nop_db_gen
  # retrofit_generator: ^2.0.0-beta3

flutter:
  uses-material-design: true
  # fonts:
    # - family: SourceHanSerif
    #   fonts:
    #     - asset: assets/fonts/SourceHanSerif-Regular.ttc
    #     - asset: assets/fonts/SourceHanSerif-Bold.ttc
    #       weight: 700
    # - family: NotoSansSC
    #   fonts:
    #     - asset: assets/fonts/NotoSansSC-Regular.otf
        # - asset: assets/fonts/NotoSansSC-Bold.otf
    #       weight: 700
    # - family: RobotoMono
    #   fonts:
    #     - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
    # - family: SourceHanSans
    #   fonts:
    #     - asset: assets/fonts/SourceHanSansCN/SourceHanSans-Regular.otf
    # - family: SourceHanSansSC
    #   fonts:
    #     - asset: assets/fonts/SourceHanSansSC-Regular.otf
    #     - asset: assets/fonts/SourceHanSansSC-Bold.otf
    #       weight: 700
